# Generated by Django 5.0.3 on 2024-07-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='last_image_update',
        ),
    ]
