version: '3.9'

services:
  postgres_project:
    container_name: postgres_ghofle_container
    image: postgres:15
    hostname: ${DB_HOST}
    command: -p ${DB_PORT}
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/project/postgres:/var/lib/postgresql/data
    networks:
      - main_ghofle_network

  redis_project:
    container_name: ${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    networks:
      - main_ghofle_network

  app_project:
    build: .
    hostname: app_project
    container_name: project_ghofle_container
    restart: on-failure
    command: sh -c "python3 manage.py makemigrations && 
                    python3 manage.py migrate --no-input && 
                    python3 manage.py collectstatic --no-input && 
                    gunicorn -k gevent --workers 4 --chdir config config.wsgi:application -b 0.0.0.0:8001"
    depends_on:
      - postgres_project
      - redis_project
    expose:
      - 8001
    ports:
      - "8001:8001"
    networks:
      - main_ghofle_network
    volumes:
      - .:/code/
      - ./media:/code/media
      - ./static:/code/static

  seq:
    image: datalust/seq:latest
    container_name: seq_ghofle_container
    hostname: ${SEQ_HOST}
    ports:
      - ${SEQ_PORT}:80
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./data/project/seq:/data
    networks:
      - main_ghofle_network

  rabbitmq_project:
    container_name: rabbitmq_himedic_container
    hostname: ${RABBITMQ_HOST}
    image: rabbitmq:latest
    networks:
      - main_ghofle_network
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

#  nginx_project:
#    image: nginx:latest
#    hostname: nginx_project
#    container_name: nginx_project_container
#    command: nginx -g 'daemon off;'
#    restart: always
#    depends_on:
#      - app_project
#    expose:
#      - "80"
#    ports:
#      - "81:80"
#    networks:
#      - main_ghofle_network
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./media:/code/media
#      - ./static:/code/static

networks:
  main_ghofle_network:

volumes:
  static:
  media:
  data:
