# Generated by Django 5.0.3 on 2024-03-30 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'zibal')], verbose_name='name')),
                ('authorization', models.CharField(max_length=240, verbose_name='authorization')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'padlock')], verbose_name='payment type')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('description', models.CharField(max_length=120, verbose_name='description')),
                ('track_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='track id')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('card_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='card number')),
                ('ref_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='ref number')),
                ('device_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='device name')),
                ('ip_address', models.CharField(blank=True, max_length=126, null=True, verbose_name='ip address')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.gateway', verbose_name='gateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
