# Generated by Django 5.0.3 on 2024-03-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_gateway_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='track_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='track id'),
        ),
    ]
