# Generated by Django 5.0.3 on 2024-03-30 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=64, unique=True, verbose_name='filename')),
                ('size', models.IntegerField(verbose_name='size')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expire at')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
        migrations.CreateModel(
            name='Padlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('review_active', models.BooleanField(default=True, verbose_name='active review')),
                ('checked', models.BooleanField(default=False, verbose_name='checked')),
                ('price', models.IntegerField(verbose_name='price')),
                ('is_auction', models.BooleanField(default=False, verbose_name='is auction')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('limit_sell', models.IntegerField(blank=True, null=True, verbose_name='limit sell')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.file', verbose_name='file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_padlocks', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnails', to='files.file', verbose_name='thumbnail')),
            ],
            options={
                'verbose_name': 'PadLock',
                'verbose_name_plural': 'PadLocks',
            },
        ),
        migrations.CreateModel(
            name='PadLockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_time', models.PositiveIntegerField(default=0, verbose_name='user time')),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='files.padlock', verbose_name='padlock')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padlock', to='finance.payment', verbose_name='payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padlocks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'PadlockUser',
                'verbose_name_plural': 'PadlockUsers',
            },
        ),
        migrations.CreateModel(
            name='PadLockUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('padlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='files.padlock', verbose_name='padlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padlock_accesses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'PadLockUserAccess',
                'verbose_name_plural': 'PadLockUserAccesses',
            },
        ),
    ]
