# Generated by Django 5.0.3 on 2024-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padlock',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='checked'),
        ),
    ]
